apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: airflowinstances.airflow.kubebuilder.io
spec:
  group: airflow.kubebuilder.io
  names:
    kind: AirflowInstance
    listKind: AirflowInstanceList
    plural: airflowinstances
    singular: airflowinstance
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                executor:
                  type: string
                scheduler:
                  type: object
                  properties:
                    replicas:
                      type: integer
                webserver:
                  type: object
                  properties:
                    service:
                      type: object
                      properties:
                        type:
                          type: string
                config:
                  type: object
                  additionalProperties:
                    type: string
